SELECT n, 'Root' FROM bst WHERE p IS NULL UNION
SELECT n, 'Leaf' FROM bst WHERE n NOT IN (SELECT p FROM bst WHERE p IS NOT NULL) UNION
SELECT n, 'Inner' FROM bst WHERE n IN (SELECT p FROM bst) AND p is NOT NULL;